version: "3.9"

services:

  dotnetmonitor:
    image: mcr.microsoft.com/dotnet/nightly/monitor/base:8-preview
    container_name: dotnetmonitor
    environment:
      - DOTNETMONITOR_DiagnosticPort__ConnectionMode=Listen
      - DOTNETMONITOR_Storage__DefaultSharedPath=/tmp
      - DOTNETMONITOR_Urls=http://localhost:52323
      - DOTNETMONITOR_Metrics__Endpoints=http://+:52325
    ports:
      - 52323:52323
    volumes:
      - ./monitordata:/tmp
    command: [ "collect", "--no-auth" ]

  orders:
    container_name: orders
    hostname: orders
    ports:
      - 5000:8080
    build:
      context: ./ContosoOnline/
      dockerfile: ./Orders/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_DiagnosticPorts=/tmp/dotnet-monitor.sock
    volumes:
      - ./monitordata:/tmp
    depends_on:
      - dotnetmonitor
      - prometheus
      
  products:
    container_name: products
    hostname: products
    build:
      context: ./ContosoOnline/
      dockerfile: ./Products/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_DiagnosticPorts=/tmp/dotnet-monitor.sock
    volumes:
      - ./monitordata:/tmp
    depends_on:
      - dotnetmonitor
      
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postuser
      POSTGRES_DB: orders

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prom_data: