global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'orders'
    static_configs:
      - targets: ['orders:8080']
  - job_name: 'products'
    static_configs:
      - targets: ['products:8080']